name: PreReward
version: '1.0-SNAPSHOT'
main: org.desp.preReward.PreReward
api-version: '1.20'
depend: [MongoLibraryPlugin, MMOMail, MMOItems, MythicLib, BinggreAPI]
commands:
  보상수령:
    aliases: ["qhtkdtnfud"]